# Using spring-ai-starter-mcp-server-webmvc

spring:
  application:
    name: spring-ai-mcp-server-demo
  ai:
    mcp:
      server:
        name: spring-ai-mcp-server-demo
        version: 1.0.0
        type: SYNC
        instructions: "This server provides weather information tools and resources"
        sse-message-endpoint: /mcp/message
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        stdio: true
        sse-endpoint: /sse
  main:
    # disable banner to allow the STDIO transport to work
    banner-mode: off

# disable console logging to allow the STDIO transport to work
logging:
  level:
    root: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,beans,env
  endpoint:
    health:
      show-details: always
